runtime: nodejs20

env: standard # Or use the flexible environment for scaling

service: default

# Decide when to scale up/down based on traffic
automatic_scaling:
  max_instances: 10
  min_instances: 0

# Ensure all files are served
handlers:
  - url: /.*
    script: auto

# Optional: Add env variables of your choice
env_variables:
  NODE_ENV: 'production'
